config/routes.rb
SampleApp::Application.routes.draw do
  resources :users, only: [:edit, :show, :new, :create, :destroy, :update, :index] do 
    collection do 
      post 'login'
    end
    resources :profiles, only: [:edit, :new, :show, :create, :update, :index, :destroy]
  end

   root 'users#index'

  

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  include Paperclip::Glue
  belongs_to :user
  has_attached_file :avatar

  scope :in_city, lambda { |city| {:conditions => ["currentcity = ?", city]} }

end

app/models/user.rb
class User < ActiveRecord::Base
	include UsersHelper
  has_one :profile, dependent: :destroy
  EMAIL_REGEX= /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :password, presence: true, length: { minimum: 8 }, length: { maximum: 16}
  validates :email ,presence: true, uniqueness: true, confirmation: true, :format => EMAIL_REGEX
  validates_confirmation_of :email

  scope :users_today, :conditions => ["created_at > ?", 1.day.ago]

 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

	def new
		@user = User.find(params[:user_id])
    @profile = @user.build_profile
	end
	
  def destroy		
	end

	def show
		@user = User.find(params[:user_id])
		@profile = Profile.find_by_user_id(params[:user_id])
	end

	def create
		@user = User.find(params[:user_id])
      @profile = @user.build_profile(profile_params)
		if @profile.save
     		redirect_to user_profile_path(:user_id =>@profile.user_id, :id =>@profile.id)
		else
			render action: 'new'
		end
	end

	def update
		@user=User.find(params[:user_id])
		@profile = Profile.find(params[:id])
    	if @profile.update_attributes(profile_params)
    		redirect_to user_profile_path, notice: 'Your Profile is updated.' #redirecting to usrs/show.html    
    	else
    		render action: 'edit'
    	end  	
	end

	def edit
		@user = User.find(params[:user_id])
    @profile = @user.profile
	end

	def index
    @profile=Profile.find_by_user_id(params[:user_id])
    if @profile
      redirect_to user_profile_path(:user_id =>params[:user_id], :id =>@profile.id)
    else
      redirect_to new_user_profile_path(:user_id =>params[:user_id])
		end
	end

	private

	def profile_params
	  params.require(:profile).permit(:avatar, :age, :name, :about, :hometown, :currentcity, :occupation, :contactno)
	end

end

app/controllers/users_controller.rb
  class UsersController < ApplicationController

  def index
    @user=User.new
  end

  def show
  @user=User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.welcome_email(@user).deliver
      redirect_to @user, notice: 'User is created.' #redirecting to usrs/show.html
    else
      render action: 'index'                        #redirecting to users/index.html
    end
  end

  def update
    @user = User.find(params[:id])
    @user.email =params[:user][:email]
     @user.update_attributes(user_params)
    redirect_to @user, notice: 'User Info is updated.' #redirecting to usrs/show.html    
  end

  def edit
    @user=User.find(params[:id])
  end

  def destroy
    @user=User.find(params[:id])
    if @user
    @user.destroy
    end
    redirect_to users_url
  end

  def login
    p params[:user_name]
    @user=User.new
    @user= @user.authenticate_safely(params[:user_name],params[:password])
    if @user
      redirect_to @user       #redirecting to usrs/show.html
    elsif  params[:user_name].eql?("super") & (params[:password].eql?("admin"))      
      return @users = User.all      
    else
      redirect_to users_url, notice: 'Invalid email or password.'                   #redirecting to users/index.html
    end
  end

  private

  def user_params
      params.require(:user).permit(:email, :password, :user_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	

    def authenticate_safely(user_name, password)
  	  User.where("user_name = ? AND password = ?", user_name, password).first
  	end
    
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app>
<head>
  <title>SampleApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
   <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular.min.js"></script>
</head>
<body>
<div class="page-header">
  <h1><small>Demo App on rails. </small></h1>
</div>
<%= yield %>

</body>
</html>

app/views/profiles/_form.html.erb
<%= form_for([@user, @profile], :role =>"form", :html => {:multipart => true}) do |f| %>

    <% if @profile.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% @profile.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
<div class="col-md-3" style="margin-left:20%">

  <div class="form-group">
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>

<div class="form-group">
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age, :class => "form-control" %>
  </div>
  </div>

  <div class="field">
    <div class="form-group">
    <%= f.label :about %><br>
    <%= f.text_field :about, :class => "form-control" %>
  </div>
  </div>

  <div class="form-group">
    <div class="field">
      <%= f.label :hometown %><br>
      <%= f.text_field :hometown, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="field">
      <%= f.label :currentcity %><br>
      <%= f.text_field :currentcity, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="field">
      <%= f.label :occupation %><br>
      <%= f.text_field :occupation, :class => "form-control" %>
    </div>
  <div class="form-group">
    <div class="field">
      <%= f.label :contactno %><br>
      <%= f.number_field :contactno, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="field">
      <strong>Upload Image:</strong>
      <%= f.file_field :avatar,:type => "file" %>
    </div>
  </div>

  <div class="actions">

    <%= f.submit value='Create'%>
  </div>
</div>
<% end %>

app/views/profiles/edit.html.erb
<ul class="nav nav-tabs ">
  
  <li><%= link_to 'Home', user_path(:id =>@profile.user_id) %></li>
  <li><%= link_to 'Profile', user_profiles_path(:user_id =>@user) %></li>
  <li class="active"><%= link_to 'Update', edit_user_profile_path(@profile.user_id, @profile) %></li>
  <li><%= link_to 'LogOut', users_path %></li>
  
</ul>
<h3 style="margin-left:20%;margin-top:5%"><strong>Updating Profile</strong></h3>

<%= render 'form' %>

app/views/profiles/new.html.erb
<ul class="nav nav-tabs">
  
  <li class="active"><%= link_to 'Profile', user_profiles_path(:user_id =>@user) %></li>
  <li><%= link_to 'Edit', edit_user_path(@user) %></li>
  <li><%= link_to 'Delete', user_path(@user), :method => :delete %></li>
  <li><%= link_to 'LogOut', users_path %></li>
</ul>
<p id="notice"><%= notice %></p>

<h2>Profile</h2>

<%= render 'form' %>

<!--<%= link_to 'Back', users_path %> -->

app/views/profiles/show.html.erb
<ul class="nav nav-tabs">
<li><%= link_to 'Home', user_path(:id =>@profile.user_id) %></li>
<li class="active"><%= link_to 'Profile', user_profiles_path(:user_id =>@user) %></li>
<li><%= link_to 'Update Profile', edit_user_profile_path(@profile.user_id, @profile) %></li>
<li ><%= link_to 'LogOut', users_path %></li>
</ul>
<p id="notice"><%= notice %></p>
<%= image_tag @profile.avatar.url %>
<p>
  <strong>Name:</strong>
  <%= @profile.name %>
</p>
<p>
  <strong>Age:</strong>
  <%= @profile.age %>
</p>
<p>
  <strong>About:</strong>
  <%= @profile.about %>
</p>

<p>
  <strong>Hometown:</strong>
  <%= @profile.hometown %>
</p>

<p>
  <strong>Current City:</strong>
  <%= @profile.currentcity %>
</p>

<p>
  <strong>Occupation:</strong>
  <%= @profile.occupation %>
</p>

<p>
  <strong>Contact No.:</strong>
  <%= @profile.contactno %>
</p>

app/views/users/_form.html.erb
<%= form_for(@user, :role =>"form") do |f|  %>
  <% if @user %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h3><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>

        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>

  <div class="form-group">
    <div class="field">
      <%= f.label :user_name %><br>
      <%= f.text_field :user_name, :class => "form-control" %>
    </div>
  </div>
<DIV class="form-group">
    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email, :class => "form-control" %>
    </div>
</DIV>
<div class="form-group">
  <div class="field">
    <%= f.label :email_confirmation %><br>
    <%= f.text_field :email_confirmation, :class => "form-control" %>
  </div>
  </div>
  <div class="form-group">
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password, :class => "form-control" %>
  </div>
  </div>
  <div class="actions">
    <%= f.submit value='Save', :class => "btn btn-default"%>
  </div>
<% end %>

app/views/users/edit.html.erb
<ul class="nav nav-tabs">
  <li ><%= link_to 'Home', @user %></li>
  <li><%= link_to 'Profile', user_profiles_path(:user_id =>@user) %></li>
  <li><%= link_to 'LogOut', users_path %></li>
  <li><%= link_to 'LogOut', users_path %></li>
</ul>
<div class="col-md-5" style= "margin-left:20%"><h3><strong>Updating user</strong></h3 >
<%= render 'form' %>
</div>

app/views/users/index.html.erb
<h1></h1>
<p id="notice"><%= notice %></p>

<div class='row'>
<div class="container" style="margin-top:10%;margin-left:20%">
  <ul class="list-inline pull-left">
    <li class="col-md-5">
      <h2>Sign Up</h2>
      <%= render 'form' %>
    </li>
    <li class="col-md-2"></li>
    <li class="col-md-5 ">
      <h2>Sign In</h2>
      <%= form_tag(:action =>'login', :role =>"form") do %>

        <div class="form-group">
          <div class="field">
        	  <strong>Username :</strong></br>
            <%= text_field_tag :user_name %>
        	</div>
        </div>

        <div class="form-group">
          <div class="password">
           <strong>Password:</strong> </br>
            <%= password_field_tag :password %>
          </div>
        </div>

          <div class="actions">
           	<%= submit_tag value='Sign in' %>
          </div>  	
      <% end %>
      </li>
    </ul>
  </div>

  </div>


  

app/views/users/login.html.erb
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Listing Users</div>
  
  <table class='table'>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.user_name, user %></td>        
        <td><%= link_to 'Edit User', edit_user_path(user) %></td>
        <td><%= link_to 'Delete User', user_path(user), :method => :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<label>New Users :</label>
<% if User.users_today %>
  <% users=User.users_today %>
  <table class='table'>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= link_to user.user_name, user %></td>        
        <td><%= link_to 'Edit User', edit_user_path(user) %></td>
        <td><%= link_to 'Delete User', user_path(user), :method => :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
</div>

app/views/users/new.html.erb
<%= link_to 'Back', users_path %>
<p id="notice"><%= notice %></p>

<h1>New user</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<ul class="nav nav-tabs">
  <li class="active"><%= link_to 'Home', @user %></li>
  <li><%= link_to 'View Profile', user_profiles_path(:user_id =>@user) %></li>
  <li><%= link_to 'Update User', edit_user_path(@user) %></li>
  <li><%= link_to 'Delete', user_path(@user), :method => :delete %></li>
  <li><%= link_to 'LogOut', users_path %></li>
</ul>
<p id="notice"><%= notice %></p>
<p><strong>Hello!</strong>
	<%= @user.user_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>